language: csharp
solution: Phinix.sln

# Workaround for submodules not being initialised by default
# We'll tell Travis to bugger off and we'll handle them ourselves
git:
  submodules: false
before_install:
  - git submodule update --init --recursive

install:
  - nuget restore ./Phinix.sln
 
script:
  - msbuild /property:Configuration=TravisCI ./Phinix.sln
