name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Fetch Nuget
      run: wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
      
    - name: Restore project via Nuget 
      run: mono nuget.exe restore ./Phinix.sln
      
    - name: Build project
      run: xbuild /property:Configuration=TravisCI ./Phinix.sln
