name: Mono on Ubuntu Latest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Grab required files
      run: |
        curl ${{ secrets.RIMWORLD_DLLS }} -o rimworld-dlls.zip
        unzip rimworld-dlls.zip -d GameDlls
        
    - name: Fetch Nuget
      run: curl https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o nuget.exe
      
    - name: Restore project via Nuget 
      run: mono nuget.exe restore ./Phinix.sln
      
    - name: Build project
      run: msbuild /property:Configuration=Release ./Phinix.sln
